jim: Create Manifest with v0.9.9.9.7
Calinou/scoop-games pull request #223
Opened 2021-03-11 14:29 UTC by MatyiFKBT

2021-03-11 14:47 UTC, MatyiFKBT commented
@Calinou seems like theCI check failed because of another app (toontownrewritten).
I created another PR #224, it should fix that.

2021-03-11 17:25 UTC, Calinou requested changes

2021-03-11 17:25 UTC, Calinou commented on bucket/jim.json
> +    ]
According to its homepage, the Visual C++ 2010 redistributable is required to run the program:

```suggestion
    ],
    "depends": "extras/vcredist2010"
```

2021-03-11 17:25 UTC, Calinou commented on bucket/jim.json
> +    "homepage": "http://www.jengerer.com/item_manager/",
Add a license field:

```suggestion
    "homepage": "http://www.jengerer.com/item_manager/",
    "license": "Proprietary",
```

2021-03-12 13:01 UTC, Calinou approved these changes
Thanks!

2021-03-12 13:01 UTC, merged