Create m64p
Calinou/scoop-games pull request #450
Opened 2021-10-30 12:44 UTC by satorope

Make portable
Closes #300

2021-10-30 15:12 UTC, Calinou requested changes
The file needs to be renamed to `m64p.json` (instead of `m64p`) before this can be merged.

2021-10-30 16:33 UTC, satorope commented
The name of the file has been modified.
Is this procedure okay?

2022-01-15 21:38 UTC, Calinou approved these changes
Thanks!

2022-01-15 21:38 UTC, Calinou commented on bucket/m64p.json
> +    "description": "Nintendo64 emulator bundled with paraLLEl-RDP for graphics",
```suggestion
    "description": "Nintendo 64 emulator bundled with paraLLEl-RDP for graphics",
```

2022-01-15 21:39 UTC, merged