newer-tanooki: Add version 1.0
Calinou/scoop-games pull request #559
Opened 2022-02-18 19:04 UTC by UnicorNora

2022-02-28 00:14 UTC, BlackPowerade requested changes

2022-02-28 00:14 UTC, BlackPowerade commented on bucket/newer-tanooki.json
> +    "license": "Visable Source",
```suggestion
    "license": "GPL-3.0-only",
```
NewerTanooki's license has been set

2022-03-06 20:23 UTC, Calinou commented on bucket/newer-tanooki.json
> +    "description": "A NewerSMBW Save Editor.",
```suggestion
    "description": "NewerSMBW save editor",
```

2022-03-06 20:23 UTC, Calinou commented on bucket/newer-tanooki.json
> +}
```suggestion
}

```

2022-03-06 21:22 UTC, Calinou approved these changes
Thanks!

2022-03-06 21:24 UTC, merged