Create polymc.json
Calinou/scoop-games pull request #565
Opened 2022-02-22 02:57 UTC by lem6ns

2022-02-22 03:20 UTC, binex-dsk requested changes

2022-02-22 03:20 UTC, binex-dsk commented on bucket/polymc.json
> +    "license": "GPL-3.0-only",
its gpl-3.0-or-later

2022-02-22 03:21 UTC, lem6ns commented on bucket/polymc.json
> +    "license": "GPL-3.0-only",
Fixed, thank you.

2022-02-27 15:37 UTC, UnicorNora commented
i think this can be merged

2022-02-27 17:08 UTC, Calinou approved these changes
Thanks!

2022-02-27 17:09 UTC, merged

2022-03-14 16:15 UTC, dada513 commented
@lem6ns sorry for contacting you here, but mind updating the package to 1.1.0? Since now it uses github releases instead of the old packages url, the package (and updater) needs to be updated